{{- if .Values.openbao.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-global
spec:
  provider:
    vault:
      server: {{ .Values.openbao.server | quote }}
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
      {{- if .Values.openbao.caBundle }}
      caBundle: {{ .Values.openbao.caBundle | quote }}
      {{- end }}
{{- end }}
