apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openbao-bootstrap
  namespace: openbao
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openbao-bootstrap
  namespace: openbao
subjects:
  - kind: ServiceAccount
    name: openbao-bootstrap
    namespace: openbao
roleRef:
  kind: Role
  name: openbao-bootstrap
  apiGroup: rbac.authorization.k8s.io