apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "openbao.fullname" .) }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "openbao.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
    - name: cluster
      port: {{ .Values.service.clusterPort }}
      targetPort: cluster
  selector:
    app.kubernetes.io/name: {{ include "openbao.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
