{{- range $nsName, $nsConfig := .Values.namespaces }}
{{- if $nsConfig.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $nsName }}
  labels:
    {{- include "openbao-config.labels" $ | nindent 4 }}
{{- end }}
{{- end }}