openbao:
  server: "http://openbao.openbao.svc.cluster.local:8200"
  path: "secret"
  version: "v2"
  authMountPath: "kubernetes"

secretStores:
  - name: kafka
    namespace: kafka
    role: kafka
    serviceAccount: kafka-sa
