apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinode-log-reader
  namespace: tinode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinode-log-reader
  template:
    metadata:
      labels:
        app: tinode-log-reader
    spec:
      containers:
        - name: reader
          image: busybox
          command: ["sh", "-c", "sleep infinity"]
          volumeMounts:
            - name: logs
              mountPath: /logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: tinode-logs