apiVersion: v1
kind: Pod
metadata:
  name: tinode-log-reader
  namespace: tinode
spec:
  restartPolicy: Never
  containers:
    - name: reader
      image: busybox
      command: ["sh", "-c", "sleep 1d"]
      volumeMounts:
        - name: logs
          mountPath: /logs
  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: tinode-logs
