apiVersion: v1
kind: Service
metadata:
  name: {{ include "tinode.fullname" . }}
  labels:
    {{- include "tinode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.targetPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpc.port }}
    targetPort: {{ .Values.service.grpc.targetPort }}
    protocol: TCP
    name: grpc
  selector:
    {{- include "tinode.selectorLabels" . | nindent 4 }}
