apiVersion: v1
kind: Service
metadata:
  name: tinode
  namespace: tinode
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tinode
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6060
      name: http
