apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: strimzi-cluster-operator
  template:
    metadata:
      labels:
        app: strimzi-cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STRIMZI_NAMESPACE
              value: "{{ join "," .Values.watchNamespaces }}"
            - name: STRIMZI_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
          resources:
{{ toYaml .Values.resources | indent 12 }}
