{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ $.Values.kafka.name }}
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
---
{{- end }}
