apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: {{ .Values.user.name }}
  namespace: {{ .Values.kafka.namespace }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: {{ .Values.user.secretName }}
          key: {{ .Values.user.passwordKey }}
