{{- if .Values.openbao.enabled }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: router-kafka-user
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: router-kafka-user
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/{{ .Values.kafka.sasl.username }}
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore

  target:
    name: ghcr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .username }}",
                "password": "{{ .token }}",
                "auth": "{{ printf '%s:%s' .username .token | b64enc }}"
              }
            }
          }

  data:
    - secretKey: username
      remoteRef:
        key: ghcr
        property: username
    - secretKey: token
      remoteRef:
        key: ghcr
        property: token


{{- end }}
