{{- if .Values.openbao.enabled }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: router-kafka-user
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: router-kafka-user
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/{{ .Values.kafka.sasl.username }}
        property: password

{{- end }}
