{{- if .Values.openbao.enabled }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: router-kafka-user
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: router-kafka-user
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/user
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: router-kafka-sasl
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: router-kafka-sasl
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ENABLE
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/sasl
        property: ENABLE
    - secretKey: MECHANISM
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/sasl
        property: MECHANISM

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: router-kafka-tls
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: router-kafka-tls
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ENABLE
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/tls
        property: ENABLE
    - secretKey: INSECURE_SKIP_VERIFY
      remoteRef:
        key: {{ .Values.openbao.secretsPath }}/tls
        property: INSECURE_SKIP_VERIFY

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.openbao.resyncInterval }}
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: registry/ghcr
        property: dockerconfigjson

{{- end }}
