{{- if .Values.openbao.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: openbao-backend
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.openbao.server | quote }}
      path: {{ .Values.openbao.path | quote }}
      version: v2
      auth:
        kubernetes:
          role: {{ .Values.openbao.role | quote }}
{{- end }}
