image:
  repository: ghcr.io/echomessenger/tinode-router
  tag: latest-amd64
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 7911
  healthPort: 8090

kafka:
  brokers: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  clientId: router
  topicPrefix: tinode
  sasl:
    enabled: true
    mechanism: SCRAM-SHA-512
    username: "user"
  tls:
    enabled: false
    insecureSkipVerify: false

log:
  level: debug

openbao:
  enabled: true
  role: "router"
  secretsPath: "kafka"
  resyncInterval: "10s"
