{{- if and .Values.init.enabled .Values.init.rootToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openbao-config.fullname" . }}-root-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbao-config.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.init.rootToken | quote }}
{{- end }}