{{- if .Values.openbao.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.openbao.server | quote }}
      path: {{ .Values.openbao.path | quote }}
      version: {{ .Values.openbao.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.openbao.kubernetesAuthMount | quote }}
          role: {{ .Values.openbao.role | quote }}
          serviceAccountRef:
            name: {{ .Values.openbao.serviceAccount.name | quote }}
            namespace: {{ .Values.openbao.serviceAccount.namespace | quote }}
      {{- if .Values.openbao.caBundle }}
      caBundle: {{ .Values.openbao.caBundle | quote }}
      {{- end }}
{{- end }}