{{- if .Values.openbao.enabled }}
{{- range .Values.secretStores }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ $.Values.openbao.server | quote }}
      path: {{ $.Values.openbao.path | quote }}
      version: {{ $.Values.openbao.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ $.Values.openbao.kubernetesAuthMount | quote }}
          role: {{ .role | quote }}
      {{- if $.Values.openbao.caBundle }}
      caBundle: {{ $.Values.openbao.caBundle | quote }}
      {{- end }}
{{- end }}
{{- end }}
