apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tinode
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      name: postgres
