openbao:
  enabled: true
  server: "https://openbao.openbao.svc.cluster.local:8200"
  path: "secret"
  role: "kafka"
  serviceAccount: "kafka-sa"
  secretsPath: "secret/kafka"
  resyncInterval: "10s"
  # Получите через: kubectl get secret openbao-server-tls -n openbao -o jsonpath='{.data.ca\.crt}'
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuakNDQW9hZ0F3SUJBZ0lVVXVpWHVyN1lWK253ZmRMUktGM2xnaDdOcnU0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xERXFNQ2dHQTFVRUF4TWhiM0JsYm1KaGJ5NXZjR1Z1WW1GdkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGcwpNQjRYRFRJMk1ERXhNREl3TXpRd05Gb1hEVEkyTURReE1ESXdNelF3TkZvd0xERXFNQ2dHQTFVRUF4TWhiM0JsCmJtSmhieTV2Y0dWdVltRnZMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzdTZLeFo5RW82V3VaRFJZZGFmaEZwRHVVZ3g4MmZSdTYxa2gyM0RpR2ZnbgpyOE1mSEFxeHg2U3NvdHlMTkhUWkxWZC9CNUVmTjdGMU9aMWZNamtiaW1KQ3Y3a1A3Z1NPdlNBWXBBcTVTR0RmCjFQd05wb0ZTcitsakxwcnRQUUhyZzFmbXRxQzh5ZU04WW5YdCtjdnphalBNczN3ZkxZUmM4Unc3dFppZ1h4K2oKSjFGbkRPQWRXYlkyNlVIcE5ydkdFRTlXU1ZjcXBLSFFtMTJON1JaU0tFb1lrRjZpd1J0TUNOQ1ArSU56Tk5vQQovcEVkRVhxRzAzcU9oSGFiSWFxZjhpQVk2d1hDMUpqeFVkL3JKdVFGbC9zM2wzVjRBVGpYeUxPUmMzaExhNCtBCmZNUEhBM1VYMXNsNmNWUTkrdFlNTUwzRFV3UW01SHZYK3BOMkt4ampvd0lEQVFBQm80RzNNSUcwTUE0R0ExVWQKRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUSm4zMEFRN1VkamhXTwp3L1VWNnhuNjQ2dWdwREJ5QmdOVkhSRUVhekJwZ2dkdmNHVnVZbUZ2Z2c5dmNHVnVZbUZ2TG05d1pXNWlZVytDCkUyOXdaVzVpWVc4dWIzQmxibUpoYnk1emRtT0NJVzl3Wlc1aVlXOHViM0JsYm1KaGJ5NXpkbU11WTJ4MWMzUmwKY2k1c2IyTmhiSUlKYkc5allXeG9iM04waHdSL0FBQUJod1FLZ1FBWU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUURNdUlkTUxzNWVua1JPbEk5NFdyenVrWjZ4aDIyOHpLc3ZRQUJvb0xsSitwT0pzelgvZ3RCSG9hcU5rUTFLCktYWDc0RjJxMFFJL1pqZEI4alJYL2N6Mmd2ZVl3Nnl4YXh5RjFWMjQrL0xZRTdONFdLZWJ6WEd4VGcya3JGa1kKUVZ1N0NmRTZWVDRBNm1adVcvN0pSdTlidGszTm5McDVEc3pSVWo5Z1JxZEZRS2VqQ01RcS9ZMi9rak9HTGJPMwpkcm5OWGJhaXBtRm9YSU9YYTcrSll1U3VGeHFGdUh0V0RFRFpmUUNNQWE0c1ZNdENWRXdlSFJ1czNHTG1lSEVUCk8zVVlLY3ljMndYL1doUkR4MGRKeUo1Q1hhN2FWd1pqVGJja2sxWEtEODZLTFIwNUtXbmc1eHV6MkxSWVMwUkkKS1lhTzFvZjBzRzFmWmp1d1BrR0tBOWpJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

kafka:
  name: kafka
  namespace: kafka
  version: 4.1.0
  replicas: 1

topics:
  - name: tinode.ctrl
    partitions: 1
    replicas: 1
  - name: tinode.data
    partitions: 3
    replicas: 1
  - name: tinode.pres
    partitions: 3
    replicas: 1
  - name: tinode.meta
    partitions: 1
    replicas: 1
  - name: tinode.info
    partitions: 1
    replicas: 1
  - name: tinode.topic_events
    partitions: 1
    replicas: 1
  - name: tinode.account_events
    partitions: 1
    replicas: 1
  - name: tinode.subscription_events
    partitions: 1
    replicas: 1
  - name: tinode.message_events
    partitions: 3
    replicas: 1
  - name: tinode.dlq
    partitions: 1
    replicas: 1
