openbao:
  enabled: true
  server: "http://openbao.openbao.svc.cluster.local:8200"
  path: "secret"
  version: "v2"
  kubernetesAuthMount: "kubernetes"
  caBundle: ""

clusterSecretStore:
  name: openbao
