apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: kafka-ui-infisical
  namespace: kafka
spec:
  resyncInterval: 10

  authentication:
    kubernetesAuth:
      identityId: {{ .Values.infisical.identityId }}
      serviceAccountRef:
        name: {{ .Values.infisical.serviceAccount.name }}
        namespace: {{ .Values.infisical.serviceAccount.namespace }}
      secretsScope:
        envSlug: {{ .Values.infisical.env }}
        projectSlug: {{ .Values.infisical.project }}
        secretsPath: /kafka

  managedKubeSecretReferences:
    - secretName: kafka-ui-password
      secretNamespace: kafka
      creationPolicy: Orphan
      template:
        includeAllSecrets: false
        data:
          password: "{{ .KAFKA_USER_PASSWORD.Value }}"
