apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-secret
  namespace: kafka
type: Opaque
stringData:
  sasl_jaas_config: >-
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username="{{ .Values.kafka.username }}"
    password="{{ .Values.kafka.username | printf "${%s_PASSWORD}" }}";
