{{- if .Values.openbao.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-global
    kind: ClusterSecretStore

  target:
    name: ghcr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ "{{" }} .username {{ "}}" }}",
                "password": "{{ "{{" }} .token {{ "}}" }}",
                "auth": "{{ "{{" }} printf \"%s:%s\" .username .token | b64enc {{ "}}" }}"
              }
            }
          }

  data:
    - secretKey: username
      remoteRef:
        key: registry/ghcr
        property: username
    - secretKey: token
      remoteRef:
        key: registry/ghcr
        property: token

{{- end }}