apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinode-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tinode
  template:
    metadata:
      labels:
        app: tinode
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: tinode
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["sleep", "3600"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6060
          envFrom:
            - secretRef:
                name: tinode-secret
          volumeMounts:
            - name: config
              mountPath: /opt/tinode/config.template
              subPath: tinode.conf
            - name: uploads
              mountPath: /app/uploads
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 6060
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 6060
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: tinode-config
        - name: uploads
          persistentVolumeClaim:
            claimName: tinode-uploads-pvc