apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinode-uploads-pvc
  namespace: tinode
spec:
  accessModes: 
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
