apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuerName }}
spec:
  acme:
    server: {{ .Values.certManager.server }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.issuerName }}-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik