apiVersion: v1
kind: Service
metadata:
  name: {{ include "tinode-router.fullname" . }}
spec:
  selector:
    app: {{ include "tinode-router.name" . }}
  ports:
    - name: http
      port: 7911
      targetPort: {{ .Values.service.port }}
